version: '3.4'

services:
  exclaimer.service.customer.web:
    image: ${DOCKER_REGISTRY-}exclaimerservicecustomerweb
    build:
      context: .
      dockerfile: Exclaimer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80;
      - ConnectionStrings__Default=Data Source=exclaimer.service.customer.db,1433;Initial Catalog=exclaimer.service.customer.db;MultipleActiveResultSets=True;User Id=sa;Password=Admin@123;TrustServerCertificate=True;
    ports:
      - "8080:80"
  exclaimer.service.customer.db:
    container_name: exclaimer.service.customer.db
    hostname: exclaimer.service.customer.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'Admin@123'
        MSSQL_DATA_DIR: /var/opt/mssql/data
        MSSQL_PID: 'Developer' 
        MSSQL_TCP_PORT: 1433 
    ports: 
        - "1455:1433"
    volumes:
        - ./data:/var/opt/mssql/data
        - ./log:/var/opt/mssql/log
        - ./secrets:/var/opt/mssql/secrets