version: '3.4'

services:
  exclaimer.service.customer.web:
    image: ${DOCKER_REGISTRY-}exclaimerservicecustomerweb
    build:
      context: .
      dockerfile: Exclaimer/Dockerfile
  exclaimer.service.customer.db:
    container_name: exclaimer.service.customer.db
    hostname: exclaimer.service.customer.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD: 'Admin@123'
        MSSQL_DATA_DIR: /var/opt/mssql/data
        MSSQL_PID: 'Developer' 
        MSSQL_TCP_PORT: 1433 
    ports: 
        - "1455:1433"
    volumes:
        - ./data:/var/opt/mssql/data
        - ./log:/var/opt/mssql/log
        - ./secrets:/var/opt/mssql/secrets